version: "3.7"

services:
    database:
        image: mysql:5.7
        configs:
            - db-config
        environment:
            MYSQL_ROOT_PASSWORD: R1234r
            MYSQL_DATABASE: phonebook_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: Clarusway_1
        volumes:
            - dbdata:/docker-entrypoint-initdb.d
    myapp:
        image: 850044925511.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo/phonebook-app:latest
        restart: always
        deploy: 
            mode: global
        depends_on:
            - database
        ports:
            - "80:80"
configs:
    db-config:
        file: ./init.sql
volumes:
    dbdata:
